apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: selenium-chrome
  labels:
    run: selenium-chrome
  namespace: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      run: selenium-chrome
  template:
    metadata:
      labels:
        run: selenium-chrome
    spec:
      containers:
        - name: selenium-chrome
          image: registry.docker-cn.com/selenium/node-chrome-debug:3.11
          imagePullPolicy: Always
          ports:
            - name: selenium-chrome
              containerPort: 5900
              hostPort: 5900
              protocol: TCP

