apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-srv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: hello-srv
          image: registry.docker-cn.com/selenium/hub:3.11
          imagePullPolicy: Always
          ports:
            - name: hub
              containerPort: 4444
              hostPort: 4444
              protocol: TCP
          volumeMounts:
            - name: cmc-config
              mountPath: /tmp
      volumes:
        - name: cmc-config
          configMap:
            name: test
            items:
              - key: cmcConfDef
                path: cmcConfDef.xml
