apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hub
  labels:
    run: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hub
  template:
    metadata:
      labels:
        run: hub
    spec:
      containers:
        - name: hello-srv
          image: hello-world
          imagePullPolicy: Always
          ports:
            - name: hub
              containerPort: 4444
              hostPort: 4444
              protocol: TCP
          volumeMounts:
            - name: cmc-config
              mountPath: /tmp
      volumes:
        - name: cmc-config
          configMap:
            name: test
            items:
              - key: cmcConfDef
                path: cmcConfDef.xml
