apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    run: java-demo
  name: java-demo
  namespace: java-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: java-demo
  template:
    metadata:
      labels:
        run: java-demo
    spec:
      containers:
      - image: registry.docker-cn.com/yaoailin/java-demo:0.1.29
        imagePullPolicy: Always
        name: java-demo
