apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hub
  labels:
    run: hub
  namespace: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hub
  template:
    metadata:
      labels:
        run: hub
    spec:
      containers:
        - name: hub
          image: registry.docker-cn.com/selenium/hub:3.11
          imagePullPolicy: Always
          ports:
            - name: hub
              containerPort: 4444
              hostPort: 4444
              protocol: TCP
          volumeMounts:
          - mountPath: /home/seluser
            name: selenium-cmc
      volumes:
      - configMap:
          items:
            - key: cmcConfDef
              path: .cmcConfDef.xml
          name: selenium-cmc
        name: selenium-cmc
