apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: qa-test
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: qa-test
          image: registry.docker-cn.com/selenium/hub:3.11
          imagePullPolicy: IfNotPresent
          ports:
            - name: qa-test
              containerPort: 4444
              hostPort: 4444
              name: qa-test
              protocol: TCP


